### ISSUE TITLE
[QUESTION] Unable to execute git commands

### ISSUE THREAD

**Issue by kagbodji** [dinhhuy258/git.nvim#3]
Hi, I am unable to use this plugin. I get the following message:

```
[git] Error during running a job: fatal: path 'lua/custom/plugins/others.lua' does not exist in 'HEAD~2'
```

The file is definitely in the index:

```bash
❯ git diff-tree --no-commit-id --name-only -r HEAD~2
tools/vim/nvchad/lua/custom/keymaps.lua
tools/vim/nvchad/lua/custom/plugins/init.lua
tools/vim/nvchad/lua/custom/plugins/others.lua
tools/vim/nvchad/lua/custom/vimopts.lua
```

I'm therefore not sure what this message means or what's causing it, here's my config.

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/30058890/181049194-bad47e42-dcd0-48c2-8f1b-bc867b523dcf.png">

Is this a bug, or is my configuration invalid?

Thanks!

**Comment by dinhhuy258** [comment]
Hi, Sorry for my late response. I was busy with other stuff.
Could you please provide me more context about the bug, such as:
- When does the bug occur? 
- Which command triggers the error? 

Thank you

**Comment by kagbodji** [comment]
Oh silly me... The issue occurs when I issue the `GitDiff` command, with or without arguments. I also use [Gitsigns](https://github.com/lewis6991/gitsigns.nvim), which also has a command `Gitsigns diffthis`, and that works
```
:!git --version
git version 2.36.1
```
Other commands, such as `GitBlame` work.

**Comment by dinhhuy258** [comment]
Ya, I understand... The error is shown when you compare the current file to two versions ago. But the file does not exist at that time, causing an error. You can try the GitDiff command with another file. Besides, I will try to improve the plugin so that I have a better handle in this case. Thanks for reporting...

**Comment by kagbodji** [comment]
I don't think that's the case as I get the error even when I'm diff'ing against the current index, and I get the error on all files.
```
[git] Error during running a job: fatal: path 'lua/custom/plugins/others.lua' does not exist in 'HEAD'
```
I am also certain the file exists in the index two revisions back. The original diff command in my report works if I execute directly at the CLI:
<img width="834" alt="image" src="https://user-images.githubusercontent.com/30058890/182638363-fcf217e2-863d-40c3-aa8b-f8d9fefe23bb.png">

I thought maybe it was config, so I tried with the default config and still get the error. I'm new to lua in neovim and am still trying to figure out how to debug/trace plugin code, happy to look into this a bit deeper once I ramp. I'll also try to reproduce in a clean env without any other plugins to see.

**Comment by dinhhuy258** [comment]
Hmm, It's weird... I don't think it's related to the config since there is no configuration needed in my plugin... 
For debugging, you can print out the git command for the `GitDiff` command using the `method: vim.notify`

![image](https://user-images.githubusercontent.com/17776979/182649240-546a518b-ed6d-4237-b9d8-28df67024f74.png)

Reload the plugin by exiting and entering nvim again. 
Run the `GitDiff` command then you can see the message at the bottom 
![image](https://user-images.githubusercontent.com/17776979/182650736-c62aa96e-7710-4fda-a5c7-2de501072a60.png)

**Comment by kagbodji** [comment]
Hi @dinhhuy258 , sorry for the delay. I tried what you said and this is the command I get:
```
git -C /Users/kagbodji/.config/nvim --literal-pathspecs --no-pager show HEAD:lua/core/options.lua
```
Interestingly, the plugin works now. I have however updated some plugins and removed others, so I think the issue may not be with your plugin. I'll debug more to see if I can get to the root cause if it comes up again, but I'm going to close this issue for now. Thanks for the help!
